[tool.poetry]
name = "ls"
version = "0.1.0"
description = ""
authors = ["ajib6ept <asalbert@ya.ru>"]

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
